name: path
services:
    api:
        build: .
        environment:
            - HOST_PORT=${HOST_PORT}
            - DATABASE_URL=host=db user=${DOCKER_POSTGRES_USER} password=${DOCKER_POSTGRES_PASSWORD} dbname=${DOCKER_POSTGRES_DB}
            - SECRET=${SECRET}
        ports:
            - ${HOST_PORT}:3000
        entrypoint: /app/path-api
        restart: unless-stopped

    db:
        image: postgres:18-alpine
        environment:
            - POSTGRES_USER=${DOCKER_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
            - POSTGRES_DB=${DOCKER_POSTGRES_DB}
        restart: unless-stopped
        volumes:
            - db:/var/lib/postgresql/18/docker

volumes:
    db:
