-- +goose Up
CREATE TYPE "role_kelas" AS ENUM (
	'pengajar',
	'murid'
);

CREATE TYPE "tipe_post" AS ENUM (
	'materi',
	'tugas'
);

CREATE TABLE IF NOT EXISTS "pengguna" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"username" TEXT NOT NULL,
	"email" TEXT NOT NULL,
	"phone" TEXT,
	"profile_picture" TEXT,
	"password" TEXT NOT NULL,
	"dibuat" TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "kelas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nama" TEXT NOT NULL,
	"tingkat" TEXT,
	"mata_pelajaran" TEXT,
	"pembuat" INTEGER NOT NULL,
	"kode_kelas" VARCHAR(6) NOT NULL,
	"dibuat" TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "anggota_kelas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"pengguna_id" INTEGER NOT NULL,
	"kelas_id" INTEGER NOT NULL,
	"role" ROLE_KELAS NOT NULL,
	"dibuat" TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "postingan" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"judul" TEXT NOT NULL,
	"deskripsi" TEXT NOT NULL,
	"lampiran" TEXT ARRAY NOT NULL,
	"tipe" TIPE_POST NOT NULL,
	"kelas_id" INTEGER NOT NULL,
	"dibuat" TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "pengumpulan_tugas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"postingan_id" INTEGER NOT NULL,
	"lampiran" TEXT ARRAY,
	"pengguna_id" INTEGER NOT NULL,
	"dibuat" TIMESTAMP NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

ALTER TABLE "pengumpulan_tugas"
ADD FOREIGN KEY("postingan_id") REFERENCES "postingan"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "kelas"
ADD FOREIGN KEY("pembuat") REFERENCES "pengguna"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "anggota_kelas"
ADD FOREIGN KEY("pengguna_id") REFERENCES "pengguna"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "anggota_kelas"
ADD FOREIGN KEY("kelas_id") REFERENCES "kelas"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "postingan"
ADD FOREIGN KEY("kelas_id") REFERENCES "kelas"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pengumpulan_tugas"
ADD FOREIGN KEY("pengguna_id") REFERENCES "pengguna"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- +goose Down
DROP TABLE pengumpulan_tugas;
DROP TABLE postingan;
DROP TABLE anggota_kelas;
DROP TABLE kelas;
DROP TABLE pengguna;
DROP TYPE tipe_post;
DROP TYPE role_kelas;
