// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RoleKelas string

const (
	RoleKelasPengajar RoleKelas = "pengajar"
	RoleKelasMurid    RoleKelas = "murid"
)

func (e *RoleKelas) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleKelas(s)
	case string:
		*e = RoleKelas(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleKelas: %T", src)
	}
	return nil
}

type NullRoleKelas struct {
	RoleKelas RoleKelas `json:"role_kelas"`
	Valid     bool      `json:"valid"` // Valid is true if RoleKelas is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleKelas) Scan(value interface{}) error {
	if value == nil {
		ns.RoleKelas, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleKelas.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleKelas) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleKelas), nil
}

type TipePost string

const (
	TipePostMateri TipePost = "materi"
	TipePostTugas  TipePost = "tugas"
)

func (e *TipePost) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TipePost(s)
	case string:
		*e = TipePost(s)
	default:
		return fmt.Errorf("unsupported scan type for TipePost: %T", src)
	}
	return nil
}

type NullTipePost struct {
	TipePost TipePost `json:"tipe_post"`
	Valid    bool     `json:"valid"` // Valid is true if TipePost is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTipePost) Scan(value interface{}) error {
	if value == nil {
		ns.TipePost, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TipePost.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTipePost) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TipePost), nil
}

type AnggotaKela struct {
	ID         int32            `json:"id"`
	PenggunaID int32            `json:"pengguna_id"`
	KelasID    int32            `json:"kelas_id"`
	Role       RoleKelas        `json:"role"`
	Dibuat     pgtype.Timestamp `json:"dibuat"`
}

type Kela struct {
	ID            int32            `json:"id"`
	Nama          string           `json:"nama"`
	Tingkat       pgtype.Text      `json:"tingkat"`
	MataPelajaran pgtype.Text      `json:"mata_pelajaran"`
	Pembuat       int32            `json:"pembuat"`
	KodeKelas     string           `json:"kode_kelas"`
	Dibuat        pgtype.Timestamp `json:"dibuat"`
}

type Pengguna struct {
	ID             int32            `json:"id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	Phone          pgtype.Text      `json:"phone"`
	ProfilePicture pgtype.Text      `json:"profile_picture"`
	Password       string           `json:"password"`
	Dibuat         pgtype.Timestamp `json:"dibuat"`
}

type PengumpulanTuga struct {
	ID          int32            `json:"id"`
	PostinganID int32            `json:"postingan_id"`
	Lampiran    []string         `json:"lampiran"`
	PenggunaID  int32            `json:"pengguna_id"`
	Dibuat      pgtype.Timestamp `json:"dibuat"`
}

type Postingan struct {
	ID        int32            `json:"id"`
	Judul     string           `json:"judul"`
	Deskripsi string           `json:"deskripsi"`
	Lampiran  []string         `json:"lampiran"`
	Tipe      TipePost         `json:"tipe"`
	KelasID   int32            `json:"kelas_id"`
	Dibuat    pgtype.Timestamp `json:"dibuat"`
}
