// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getPengguna = `-- name: GetPengguna :one
select id, username, email, phone, profile_picture, password, dibuat from pengguna where id = $1
`

func (q *Queries) GetPengguna(ctx context.Context, id int32) (Pengguna, error) {
	row := q.db.QueryRow(ctx, getPengguna, id)
	var i Pengguna
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.ProfilePicture,
		&i.Password,
		&i.Dibuat,
	)
	return i, err
}

const listPengguna = `-- name: ListPengguna :many
select id, username, email, phone, profile_picture, password, dibuat from pengguna
`

func (q *Queries) ListPengguna(ctx context.Context) ([]Pengguna, error) {
	rows, err := q.db.Query(ctx, listPengguna)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pengguna
	for rows.Next() {
		var i Pengguna
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.ProfilePicture,
			&i.Password,
			&i.Dibuat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
