// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createPengguna = `-- name: CreatePengguna :one
INSERT INTO pengguna (username, email, password)
VALUES ($1, $2, $3)
RETURNING id
`

type CreatePenggunaParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreatePengguna(ctx context.Context, arg CreatePenggunaParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPengguna, arg.Username, arg.Email, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getEmailPengguna = `-- name: GetEmailPengguna :one
SELECT 1 FROM pengguna WHERE email = $1
`

func (q *Queries) GetEmailPengguna(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getEmailPengguna, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPengguna = `-- name: GetPengguna :one
SELECT id, password FROM pengguna WHERE email = $1
`

type GetPenggunaRow struct {
	ID       int32  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) GetPengguna(ctx context.Context, email string) (GetPenggunaRow, error) {
	row := q.db.QueryRow(ctx, getPengguna, email)
	var i GetPenggunaRow
	err := row.Scan(&i.ID, &i.Password)
	return i, err
}
